/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_NeopixelShield_H
#define _JERRYSCRIPT_MBED_NeopixelShield_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"

#include "BlinkyShield.h"

DECLARE_CLASS_CONSTRUCTOR(NeopixelShield);
jerry_value_t mbed_js_wrap_native_object(NeopixelShield* ptr);

#endif // _JERRYSCRIPT_MBED_NeopixelShield_H
