/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_LIB_BLINKYSHIELD_H
#define _JERRYSCRIPT_MBED_LIB_BLINKYSHIELD_H

#include "mbed-js-blinkyshield/mbed-js-blinkyshield.h"
#include "jerryscript-mbed-library-registry/wrap_tools.h"

void mbed_js_NeopixelShield_setup();

DECLARE_JS_WRAPPER_REGISTRATION (blinkyshield)
{
    REGISTER_CLASS_CONSTRUCTOR(NeopixelShield);
    mbed_js_NeopixelShield_setup();
}

#endif // _JERRYSCRIPT_MBED_LIB_BLINKYSHIELD_H
